---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph
# make sure namespace exists
resources:
- resources/namespace.yaml

helmCharts:
- name: rook-ceph
  releaseName: rook-ceph
  repo: "https://charts.rook.io/release/"
  version: 1.11.1
  includeCRDs: true
  valuesMerge: override
  valuesFile: resources/operator-values.yaml
