---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
# make sure namespace exists
resources:
- resources/namespace.yaml
- dashboards/cluster-cm.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  namespace: monitoring
  repo: "https://prometheus-community.github.io/helm-charts"
  version: 45.7.1
  includeCRDs: true
  valuesMerge: override
  valuesFile: resources/values.yaml

